repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: fix-encoding-pragma
    -   id: flake8
    -   id: requirements-txt-fixer
-   repo: git://github.com/asottile/reorder_python_imports
    sha: v1.3.4
    hooks:
    -   id: reorder-python-imports
-   repo: git@git.yelpcorp.com:mirrors/asottile/add-trailing-comma
    rev: v0.7.1
    hooks:
    -   id: add-trailing-comma
-   repo: git@git.yelpcorp.com:mirrors/pre-commit/mirrors-autopep8
    rev: v1.4.3
    hooks:
    -   id: autopep8
-   repo: https://github.com/Yelp/detect-secrets
    sha: v0.12.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*tests/.*|\.pre-commit-config\.yaml
