language: python
python:
    - '2.7'
    - '3.6'

install:
    - pip install tox-travis

script: make test
deploy:
    provider: pypi
    user: yelplabs
    password:
        secure: QG9rd2z6pH4E5NCph+mw739wsaTlTpy1c5+AR1q+w/ZSrMpucNdp1i8BXAgpj2kIvuaIQQd3Behu+SVd7u5TSCZoAE7PxUKBFvEiN/7g++RVlDlPcpXTVQT8qXfvFnTGCnS95pLhXVIMDJU4cUjjDS6kshBVuvn2MTwskY4emow=
    on:
        tags: true
